FROM node:20-alpine AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npx nx build api-gateway

FROM node:20-alpine
WORKDIR /srv
ENV NODE_ENV=production
COPY --from=build /app/dist/api-gateway ./dist
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
EXPOSE 3000
CMD ["node", "dist/main.js"]
