FROM node:20-alpine AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run nx build api-products

FROM node:20-alpine
WORKDIR /srv
ENV NODE_ENV=production
COPY --from=build /app/dist/api-products ./dist
COPY --from=build /app/dist/api-products/package.json ./
COPY --from=build /app/dist/api-products/package-lock.json ./
RUN npm ci --omit=dev
EXPOSE 3002
CMD ["node", "dist/main.js"]
