apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-microservices.fullname" . }}-rabbitmq
  labels:
    {{- include "my-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: {{ .Values.replicaCount.rabbitmq }}
  selector:
    matchLabels:
      {{- include "my-microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "my-microservices.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-microservices.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-rabbitmq
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "rabbitmq:3-management"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources.rabbitmq | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env.rabbitmq }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.persistence.rabbitmq.enabled }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          {{- end }}
      {{- if .Values.persistence.rabbitmq.enabled }}
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: {{ include "my-microservices.fullname" . }}-rabbitmq
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
