apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-microservices.fullname" . }}-web-portal
  labels:
    {{- include "my-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-portal
spec:
  replicas: {{ .Values.replicaCount.webPortal }}
  selector:
    matchLabels:
      {{- include "my-microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web-portal
  template:
    metadata:
      labels:
        {{- include "my-microservices.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web-portal
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-microservices.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-web-portal
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}-web-portal:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.webPortal | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env.webPortal }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
