apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users
  labels:
    app: api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
      - name: api-users
        image: api-users:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-users-service
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP