apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
  labels:
    app: web-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-portal
  template:
    metadata:
      labels:
        app: web-portal
    spec:
      containers:
      - name: web-portal
        image: web-portal:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-portal-service
spec:
  selector:
    app: web-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer